marcer_list = input("Please enter the list of marcer: ").split()
for marcer in marcer_list:
    print(marcer + " TEXT,")

config = {
    'host': 'localhost',
    'user': 'root',
    "password": PASSWORD,
    'database': 'info_db'
}

conn = mysql.connector.connect(**config)
cursor = conn.cursor()

# テーブル作成のクエリ
create_table_query = """
CREATE TABLE IF NOT EXISTS my_table (
    DisclosedDate TEXT,
    DisclosedTime TEXT,
    LocalCode TEXT,
    DisclosureNumber TEXT,
    TypeOfDocument TEXT,
    TypeOfCurrentPeriod TEXT,
    CurrentPeriodStartDate TEXT,
    CurrentPeriodEndDate TEXT,
    CurrentFiscalYearStartDate TEXT,
    CurrentFiscalYearEndDate TEXT,
    NextFiscalYearStartDate TEXT,
    NextFiscalYearEndDate TEXT,
    NetSales TEXT,
    OperatingProfit TEXT,
    OrdinaryProfit TEXT,
    Profit TEXT,
    EarningsPerShare TEXT,
    DilutedEarningsPerShare TEXT,
    TotalAssets TEXT,
    Equity TEXT,
    EquityToAssetRatio TEXT,
    BookValuePerShare TEXT,
    CashFlowsFromOperatingActivities TEXT,
    CashFlowsFromInvestingActivities TEXT,
    CashFlowsFromFinancingActivities TEXT,
    CashAndEquivalents TEXT,
    ResultDividendPerShare1stQuarter TEXT,
    ResultDividendPerShare2ndQuarter TEXT,
    ResultDividendPerShare3rdQuarter TEXT,
    ResultDividendPerShareFiscalYearEnd TEXT,
    ResultDividendPerShareAnnual TEXT,
    ResultTotalDividendPaidAnnual TEXT,
    ResultPayoutRatioAnnual TEXT,
    ForecastDividendPerShare1stQuarter TEXT,
    ForecastDividendPerShare2ndQuarter TEXT,
    ForecastDividendPerShare3rdQuarter TEXT,
    ForecastDividendPerShareFiscalYearEnd TEXT,
    ForecastDividendPerShareAnnual TEXT,
    ForecastTotalDividendPaidAnnual TEXT,
    ForecastPayoutRatioAnnual TEXT,
    NextYearForecastDividendPerShare1stQuarter TEXT,
    NextYearForecastDividendPerShare2ndQuarter TEXT,
    NextYearForecastDividendPerShare3rdQuarter TEXT,
    NextYearForecastDividendPerShareFiscalYearEnd TEXT,
    NextYearForecastDividendPerShareAnnual TEXT,
    NextYearForecastPayoutRatioAnnual TEXT,
    ForecastNetSales2ndQuarter TEXT,
    ForecastOperatingProfit2ndQuarter TEXT,
    ForecastOrdinaryProfit2ndQuarter TEXT,
    ForecastProfit2ndQuarter TEXT,
    ForecastEarningsPerShare2ndQuarter TEXT,
    NextYearForecastNetSales2ndQuarter TEXT,
    NextYearForecastOperatingProfit2ndQuarter TEXT,
    NextYearForecastOrdinaryProfit2ndQuarter TEXT,
    NextYearForecastProfit2ndQuarter TEXT,
    NextYearForecastEarningsPerShare2ndQuarter TEXT,
    ForecastNetSales TEXT,
    ForecastOperatingProfit TEXT,
    ForecastOrdinaryProfit TEXT,
    ForecastProfit TEXT,
    ForecastEarningsPerShare TEXT,
    NextYearForecastNetSales TEXT,
    NextYearForecastOperatingProfit TEXT,
    NextYearForecastOrdinaryProfit TEXT,
    NextYearForecastProfit TEXT,
    NextYearForecastEarningsPerShare TEXT,
    MaterialChangesInSubsidiaries TEXT,
    ChangesBasedOnRevisionsOfAccountingStandard TEXT,
    ChangesOtherThanOnesBasedOnRevisionsOfAccountingStandard TEXT,
    ChangesInAccountingEstimates TEXT,
    RetrospectiveRestatement TEXT,
    NumberOfTreasuryStockAtTheEndOfFiscalYear TEXT,
    AverageNumberOfShares TEXT,
    NonConsolidatedNetSales TEXT,
    NonConsolidatedOperatingProfit TEXT,
    NonConsolidatedOrdinaryProfit TEXT,
    NonConsolidatedProfit TEXT,
    NonConsolidatedEarningsPerShare TEXT,
    NonConsolidatedTotalAssets TEXT,
    NonConsolidatedEquity TEXT,
    NonConsolidatedEquityToAssetRatio TEXT,
    NonConsolidatedBookValuePerShare TEXT,
    ForecastNonConsolidatedNetSales2ndQuarter TEXT,
    ForecastNonConsolidatedOperatingProfit2ndQuarter TEXT,
    ForecastNonConsolidatedOrdinaryProfit2ndQuarter TEXT,
    ForecastNonConsolidatedProfit2ndQuarter TEXT,
    ForecastNonConsolidatedEarningsPerShare2ndQuarter TEXT,
    NextYearForecastNonConsolidatedNetSales2ndQuarter TEXT,
    NextYearForecastNonConsolidatedOperatingProfit2ndQuarter TEXT,
    NextYearForecastNonConsolidatedOrdinaryProfit2ndQuarter TEXT,
    NextYearForecastNonConsolidatedProfit2ndQuarter TEXT,
    NextYearForecastNonConsolidatedEarningsPerShare2ndQuarter TEXT,
    ForecastNonConsolidatedNetSales TEXT,
    ForecastNonConsolidatedOperatingProfit TEXT,
    ForecastNonConsolidatedOrdinaryProfit TEXT,
    ForecastNonConsolidatedProfit TEXT,
    ForecastNonConsolidatedEarningsPerShare TEXT,
    NextYearForecastNonConsolidatedNetSales TEXT,
    NextYearForecastNonConsolidatedOperatingProfit TEXT,
    NextYearForecastNonConsolidatedOrdinaryProfit TEXT,
    NextYearForecastNonConsolidatedProfit TEXT,
    NextYearForecastNonConsolidatedEarningsPerShare TEXT
    )
"""
cursor.execute(create_table_query)
