# Input string
input_string = "DisclosedDate	DisclosedTime	LocalCode	DisclosureNumber	TypeOfDocument	TypeOfCurrentPeriod	CurrentPeriodStartDate	CurrentPeriodEndDate	CurrentFiscalYearStartDate	CurrentFiscalYearEndDate	NextFiscalYearStartDate	NextFiscalYearEndDate	NetSales	OperatingProfit	OrdinaryProfit	Profit	EarningsPerShare	DilutedEarningsPerShare	TotalAssets	Equity	EquityToAssetRatio	BookValuePerShare	CashFlowsFromOperatingActivities	CashFlowsFromInvestingActivities	CashFlowsFromFinancingActivities	CashAndEquivalents	ResultDividendPerShare1stQuarter	ResultDividendPerShare2ndQuarter	ResultDividendPerShare3rdQuarter	ResultDividendPerShareFiscalYearEnd	ResultDividendPerShareAnnual	DistributionsPerUnit(REIT)	ResultTotalDividendPaidAnnual	ResultPayoutRatioAnnual	ForecastDividendPerShare1stQuarter	ForecastDividendPerShare2ndQuarter	ForecastDividendPerShare3rdQuarter	ForecastDividendPerShareFiscalYearEnd	ForecastDividendPerShareAnnual	ForecastDistributionsPerUnit(REIT)	ForecastTotalDividendPaidAnnual	ForecastPayoutRatioAnnual	NextYearForecastDividendPerShare1stQuarter	NextYearForecastDividendPerShare2ndQuarter	NextYearForecastDividendPerShare3rdQuarter	NextYearForecastDividendPerShareFiscalYearEnd	NextYearForecastDividendPerShareAnnual	NextYearForecastDistributionsPerUnit(REIT)	NextYearForecastPayoutRatioAnnual	ForecastNetSales2ndQuarter	ForecastOperatingProfit2ndQuarter	ForecastOrdinaryProfit2ndQuarter	ForecastProfit2ndQuarter	ForecastEarningsPerShare2ndQuarter	NextYearForecastNetSales2ndQuarter	NextYearForecastOperatingProfit2ndQuarter	NextYearForecastOrdinaryProfit2ndQuarter	NextYearForecastProfit2ndQuarter	NextYearForecastEarningsPerShare2ndQuarter	ForecastNetSales	ForecastOperatingProfit	ForecastOrdinaryProfit	ForecastProfit	ForecastEarningsPerShare	NextYearForecastNetSales	NextYearForecastOperatingProfit	NextYearForecastOrdinaryProfit	NextYearForecastProfit	NextYearForecastEarningsPerShare	MaterialChangesInSubsidiaries	ChangesBasedOnRevisionsOfAccountingStandard	ChangesOtherThanOnesBasedOnRevisionsOfAccountingStandard	ChangesInAccountingEstimates	RetrospectiveRestatement	NumberOfIssuedAndOutstandingSharesAtTheEndOfFiscalYearIncludingTreasuryStock	NumberOfTreasuryStockAtTheEndOfFiscalYear	AverageNumberOfShares	NonConsolidatedNetSales	NonConsolidatedOperatingProfit	NonConsolidatedOrdinaryProfit	NonConsolidatedProfit	NonConsolidatedEarningsPerShare	NonConsolidatedTotalAssets	NonConsolidatedEquity	NonConsolidatedEquityToAssetRatio	NonConsolidatedBookValuePerShare	ForecastNonConsolidatedNetSales2ndQuarter	ForecastNonConsolidatedOperatingProfit2ndQuarter	ForecastNonConsolidatedOrdinaryProfit2ndQuarter	ForecastNonConsolidatedProfit2ndQuarter	ForecastNonConsolidatedEarningsPerShare2ndQuarter	NextYearForecastNonConsolidatedNetSales2ndQuarter	NextYearForecastNonConsolidatedOperatingProfit2ndQuarter	NextYearForecastNonConsolidatedOrdinaryProfit2ndQuarter	NextYearForecastNonConsolidatedProfit2ndQuarter	NextYearForecastNonConsolidatedEarningsPerShare2ndQuarter	ForecastNonConsolidatedNetSales	ForecastNonConsolidatedOperatingProfit	ForecastNonConsolidatedOrdinaryProfit	ForecastNonConsolidatedProfit	ForecastNonConsolidatedEarningsPerShare	NextYearForecastNonConsolidatedNetSales	NextYearForecastNonConsolidatedOperatingProfit	NextYearForecastNonConsolidatedOrdinaryProfit	NextYearForecastNonConsolidatedProfit	NextYearForecastNonConsolidatedEarningsPerShare"

# Split the string at whitespace
word_list = input_string.split()

# 64文字以上の単語をプリント
 
# Iterate over the list
for word in word_list:
    # Check if the length of the word is greater than 64
    if len(word) > 64:

        # Print the word
        print(word)

# "()"を含む単語をプリント
# Iterate over the list
for word in word_list:
    # Check if the word contains "(" or ")"
    if "(" in word or ")" in word:

        # Print the word
        print(word)